### ISSUE TITLE
Problem with algorithms.pdf

### ISSUE THREAD

**Issue by chiragvartak** [aimacode/aima-pseudocode#1]
Is there a problem with the algorithms.pdf file? Is anyone else having a problem with opening it?    
I am just asking this to find if there is a problem with the pdf file itself or with my computer. I can't seem to open it using any PDF viewer on either Linux or Windows.

**Comment by chiragvartak** [comment]
Sorry, false alarm.  
As it turns out, even downloading by right-clicking the link to the pdf file on the main page of this repo, downloads the file as an HTML page but saves it with a .pdf extension. Weird. This makes the OS think that it is a pdf file when in fact it is not.  
I couldn't find a way to download a single pdf file from Github. You need to download the entire repo if you wish to have that pdf file.  
Closing this issue.

**Comment by SnShine** [comment]
@chiragvartak you can open the PDF file by clicking on it in GitHub site. Now, clicking 'Raw' would download that PDF to your local machine.
