### ISSUE TITLE
adding math symbols in github flavoured markdown

### ISSUE THREAD

**Issue by SnShine** [aimacode/aima-pseudocode#14]
It seems we cannot add math symbols like pi, sigma, alpha in github markdown. Any workaround?

After adding and modifying these markdown files, are we gonna use them in 4th edition of the book? If so, we should figure out a way to put these math symbols. 

This says we can't do this in GFM: https://github.com/github/markup/issues/274

**Comment by anurag-rai** [comment]
I'm not really sure what that issue pertains to, but for pi, sigma, alpha etc, we can use the tags "&alpha; &pi; &sigma;" respectively, as we have been using it, like [here](https://github.com/aimacode/aima-pseudocode/blob/master/md/Alpha-Beta-Search.md).

**Comment by SnShine** [comment]
Wow! I don't know about it. Thanks.

**Comment by J-bot75** [comment]
$\sigma$
